# Generated by Django 4.2.2 on 2023-06-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('percentage_user', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage_substudio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage_referred', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage_other', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('document', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('id_owner', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('year', models.IntegerField()),
                ('mount', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth', models.DateField()),
                ('account_bank', models.CharField(max_length=128)),
                ('id_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.owner')),
                ('id_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.page')),
                ('id_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('type', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('expiration', models.DateField()),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='code_other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_accounts', to='principal.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='code_referred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_accounts', to='principal.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='code_substudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substudio_accounts', to='principal.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='code_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='principal.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.master'),
        ),
    ]
