# Generated by Django 4.2.2 on 2023-09-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_bank_id_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('value', models.IntegerField()),
                ('state', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('id_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.bank')),
                ('id_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.period')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.user')),
            ],
        ),
    ]
