# Generated by Django 4.2.2 on 2023-09-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_payment_id_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code_studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_accounts', to='principal.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='percentage_studio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_other',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_referred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_substudio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_user',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
