# Generated by Django 4.2.2 on 2023-09-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_account_code_studio_account_percentage_studio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage_studio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage_user', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage_substudio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage_referred', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage_other', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('code_other', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_earning', to='principal.user')),
                ('code_referred', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_earning', to='principal.user')),
                ('code_studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_earning', to='principal.user')),
                ('code_substudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substudio_earning', to='principal.user')),
                ('code_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_earning', to='principal.user')),
                ('id_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.account')),
                ('id_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.period')),
            ],
        ),
    ]
